language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

os:
  - linux
  - windows

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

install:
  - pip install .
  - pip install -r test-requirements.txt
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

script:
  - python tests
  - nosetests --with-coverage --cover-package=chatterbot

after_success:
  - coveralls
